### PR TITLE
use StringRes for setTitles() in the builder

### LINKED ISSUE #30: Can we use string-res in MultiChoiceToolbar.Builder.setTitles()
> from https://github.com/dvdciri/MultiChoiceRecyclerView/issues/28#issuecomment-274800577

### PR DESCRIPTION
**Pull request by hardysim**
fixes #30

### CODE REVIEW

**Comment by hardysim** [comment]
I changed the signature of `MultiChoiceToolbar.Builder#setTitles()` to `(String, String)` and `(@StringRes int, @PluralsRes int)` for the ease of implementation.

For the user, he can choose `(int, int)` which should be the default way to use it or `(String, String)` when the  titles needs to be made up on-the-fly.

**Comment by dvdciri** [comment]
Ok Good, just increase the MINOR version of the release. I'll merge it.

Did you test it with the sample app? Is everything ok? backwards-compatible?

**Comment by hardysim** [comment]
> backwards-compatible?

It was not because I've removed the `setTitles(String, @PluralsRes int)` in favor of `setTitles(@StringRes int, @PluralsRes int)` but I reverted it nowso we're fully backwards-compatible.

I've added a `@Deprecated` to it as well. All samples already use the new `(int, int)`-style so any user will have see the indented way of using it (and not the deprecated version).

**Comment by dvdciri** [comment]
Wait, you shouldn't merge everything into this branch you should rebase onto develop, in order to rewrite the history and not end up having 14 commits not needed! Maybe at this point, create another PR from updated develop, cherry pick just the commits that you want for this PR, and if you fancy squash them into one. Otherwise i'll do it.

**Comment by hardysim** [comment]
Hmm, I did it after realizing that the changelog isn't up-to-date with the master. And as develop is not meant to be behind master I merged both :wink: (a reason for #42).

So the problem seems to be my merge of master into my feature-branch. A merge of develop should not result in any unwanted commits, does it?

---

I did a rebase and squashed my 2 commits. Should be fine now...

**Comment by hardysim** [comment]
Sry for the mess with the merge-commits (should be ok when merge + squash). The last one comes from syncing my branches with yours. My tree looks good now and I'm prepared for the future :smile:.

**Comment by hardysim** [comment]
@dvdciri can you have a look (and merge)?

**Comment by dvdciri** [comment]
There are still 7 commits here.. can you please squash everything in one commit that includes CHANGELOG, config bump, library and sample changes?
Thanks

**Comment by hardysim** [comment]
> can you please squash everything in one commit

You said you can do a sqash+merge when merging. This would be far easier then me screwing up an other squash...

**Comment by dvdciri** [comment]
I can squash into one commit but i can't change the message and rebase it. So please use the UI in SourceTree for doing an interactive rebase onto the last commit of develop and quash everything into a single commit adding a proper commit message and i'll be happy to merge.

**Comment by hardysim** [comment]
> I can squash into one commit but i can't change the message

so you'll never do a squash-merge because the message would be "too ugly"?

---

rebased and good to go now

**Comment by hardysim** [comment]
@dvdciri any updates on this?

**Pull request merged**
